### ISSUE TITLE
Example gets stuck at 100% CPU usage and outputs text very slowly

### ISSUE THREAD

**Issue by Dart25** [dranger003/llama.cpp-dotnet#1]
Hello! I've been having trouble getting this library to work properly, I followed the build instructions in README.md to build (though, it seems `dotnet restore` also has to be run, or it complains about a missing json file) however when I run `LlamaCppCli.exe`, the model seems to load as it should; but outputs text at an abnormally slow pace (after letting it run for about 15 minutes with the default prompt it hadn't even finished one word!).

For comparison, llama-node (a node.js wrapper for llama.cpp / llama-rs) runs fine in the same environment.
Running the regular main.exe program provided by llama.cpp also works fine.

I would be very grateful for a solution to this problem :P

Windows 10 Home x64
Intel Core i3-6100 (clocked at 3.70GHz)
.NET SDK 7.0.203 (Bundled with Visual Studio)
Visual Studio Community 2022 17.5.4 (64-bit)

Model: ggml-vicuna-13b-1.1-q4_0.bin (SHA256: `4a11e1dbccadd4bef532bb0a2057cca0ebbfa435ce3fb993a74a97ee8cc285f7`)

Latest version of this repo (commit 27cab88)

**Comment by Dart25** [comment]
[LlamaCppDotNetLog.txt](https://github.com/dranger003/llama.cpp-dotnet/files/11299151/LlamaCppDotNetLog.txt)
Here's the log generated, when I let it run for longer it only got as far as "ASSIST" in half an hour

**Comment by dranger003** [comment]
I have added a number of fixes, try pulling the latest code.

**Comment by Dart25** [comment]
> I have added a number of fixes, try pulling the latest code.

Alright, I have pulled & recompiled the latest commit (1b27894), and it appears the same issue with the very slow token generation persists :(

However, the log did change a bit since last time, and `ggml ctx size` seems to be the same value as main.exe now (hopefully good?):
[Log2.txt](https://github.com/dranger003/llama.cpp-dotnet/files/11299701/Log2.txt)

Thanks for your time!

(edit: Also, the ggml-vicuna-13b-v1.1-q4_1.bin model mentioned in the log is the same one mentioned in the new README, and I forgot to mention in the original issue that my system has 24gb of DDR4 RAM, if that matters at all)

**Comment by dranger003** [comment]
First, make sure you're running a `Release` build as `Debug` builds are horribly slow.

Also, it looks like you're running a `q4_2` model according to your log, you may want to try a `q4_0` which is the fastest.
Otherwise, I think maybe the VS project settings are not suited for your machine - you can try this:

```
Solution -> Projects -> llama.cpp -> llama
Right-click -> Properties -> C/C++ -> Code Generation -> Enable Enhanced Instruction Set
```

Change the enhanced instruction set to inherit.
You can also play with the settings under `Optimization` (i.e. inline expansion, intrinsic functions, etc.)

If all fails, then maybe just compile llama.dll directly from llama.cpp (in a VS prompt):

```
cd llama.cpp\upstream
cmake -DBUILD_SHARED_LIBS=ON -DLLAMA_CUBLAS=ON .
cmake --build . --config Release
copy /y bin\Release\llama.dll ..\..\x64\Release
```

**Comment by Dart25** [comment]
Sadly, that didn't work either, I'm pretty sure it's a release build ([BuildLog.txt](https://github.com/dranger003/llama.cpp-dotnet/files/11301380/BuildLog.txt)), I changed `Enable Enhanced Instruction Set` to `Advanced Vector Extensions 2 (X86/X64) (/arch:AVX2)` since that's the highest that my processor supports, and the slow generation persisted... I also tried building llama.dll from llama.cpp as mentioned in your comment (replacing `-DLLAMA_CUBLAS=ON` with `-DLLAMA_AVX2=ON` since I'm targeting AVX2), with the same results.

I tried a couple different models, the slow generation persisted with all.
Log generated using `vicuna-13b-free-q4_0.bin`: [Log3.txt](https://github.com/dranger003/llama.cpp-dotnet/files/11301387/Log3.txt) (note the log indicating this model IS actually `q4_0`, unlike `ggml-vicuna-13b-v1.1-q4_1.bin`, and was the same model used with llama-node)

Log generated using llama.cpp's `main.exe` with the same `vicuna-13b-free-q4_0.bin` model: [Log4.txt](https://github.com/dranger003/llama.cpp-dotnet/files/11301407/Log4.txt) (seems the model randomly started outputting the Apache License :P, I terminated it after `http://www.apache.org/`; also note that the main.exe used was the same one generated with the `llama.cpp-dotnet` build)

I'm really not sure what could be causing this behavior...

**Comment by dranger003** [comment]
This is quite unusual, I think we're missing something trivial. Can you try the following code and change the `options.ThreadCount` according to your CPU (i.e. # of cores divided by two, if you have hyperthreading).

```
using (var model = new LlamaCpp(ModelName))
{
    model.Load("ggml-vicuna-13b-v1.1-q4_0.bin");

    model.Configure(options =>
    {
        options.ThreadCount = 4;
        options.TopK = 50;
        options.TopP = 0.95f;
        options.Temperature = 0.1f;
        options.RepeatPenalty = 1.1f;
    });

    var session = model.CreateSession("Conversation #1");

    while (true)
    {
        Console.Write("> ");
        var prompt = Console.ReadLine();

        if (String.IsNullOrWhiteSpace(prompt))
            break;

        await foreach (var token in session.Predict(prompt))
            Console.Write(token);
    }
}
```

**Comment by Dart25** [comment]
... Wow I feel like such an idiot now, that totally fixed it! Thanks so much for your help, and good work on the wrapper!
I'm closing this, issue resolved :D
