### ISSUE TITLE
Should eos token be returned?

### ISSUE THREAD

**Issue by Camel-RD** [dranger003/llama.cpp-dotnet#12]
This code adds eos token to the response if it is not included in ExtraStopTokens:
  ```
var stop = false
	|| sequence.PosTokens >= sequence.Tokens.Length - 1
	|| sequence.PosTokens - sequence.PosResponse >= sequence.SamplingOptions.ResponseMaxTokenCount
	|| (sequence.StopTokens?.Contains(token) ?? false);

if (!stop)
{
	sequence.Prompt.TokenChannel.Writer.TryWrite(llama_token_to_piece(_model.Handle, token).ToArray());
	sequence.Tokens[sequence.PosTokens++] = token;
}
```

**Comment by dranger003** [comment]
I think maybe this could be improved by making this behavior configurable when crafting the prompt. Some models currently stop on a non-eos token and having these non-eos tokens polutes the output, so this is why it is omitted here.

**Comment by dranger003** [comment]
Closing for now, re-open if you need to further discuss.
