### ISSUE TITLE
Fatal error. System.AccessViolationException: Attempted to read or write protected memory

### ISSUE THREAD

**Issue by arctocore** [dranger003/llama.cpp-dotnet#13]
I am using visual studio 2022 community edition.

I get this message when trying to run the SampleRaw:
[00:00:12.2434398]> create c# console
4/32768 token(s)
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:

**Comment by dranger003** [comment]
Run the code in debug mode and paste the line where you get the crash.

**Comment by dranger003** [comment]
Closing for now, re-open if you still are having an issue.
