### ISSUE TITLE
Add Load/Save state bindings

### ISSUE THREAD

**Issue by HarvieKrumpet** [dranger003/llama.cpp-dotnet#14]
Found your bindings to be the by far the cleanest way to work with LLama.cpp. Replaced my entire pipeline with your workflow.
Wanted to add in Load/Save State ability. Found it to be non-trivial. I don't suppose you could add the missing bindings with all the marshaling?  At a minimum maybe a quick file based load/save state method?

**Comment by dranger003** [comment]
@HarvieKrumpet Thanks, the state calls have been on my list for a while. I should be able to add them soon.

**Comment by HarvieKrumpet** [comment]
Question on state save/loads.  Out of the box the inference engine is stateless.  and we just continuously feed the chat flow back to it. using a sliding window technique.  Now let's say we reach a point where losing any more context would just make it incoherent . Lets say were an hour into this. and we save the state, before restarting it. We start at the new point, but the state has built up the knowledge from the first part.  Will I get any coherency out of this technique?  I know the model will not actually remember the old chat flow. but it will have made some internal adjustments. Would I get any benefit by continuously saving the state at the end. Or will it just be the same as if I just let the inference engine continue on. and let it lose the earlier context?

**Comment by dranger003** [comment]
The engine itself is stateless, yes, but llama.cpp has context management strategies in their main example. I think there are two mains reasons to motivate keeping things stateless overall.

- Context length is currently quite short across models we have access to, and sharing it in a parallel prompt setup isn't ideal and would be quite complex to manage, especially if you want the context to be dynamic across the threads.
- The overall recompute of the context may be a bottleneck for low end hardware, but quickly becomes a non-issue as you scale.

Now to answer your question, I haven't tested this yet and I thought about it the same as you did - will reloading a previously saved state require a decode call? I presume it will, because the state is 1-to-1 dependant on the exact version of the model you use to save the state. Unless maybe they store the model hash in the state then validate it during reload.

**Comment by HarvieKrumpet** [comment]
I currently have a very elaborate system to manage context in this stateless environment. but its not infinite. I have in the past experimented with saved states. For instance a very elaborate system message and save the state. then reload the state but remove the actual context message. The model will actually behave as if it has that system message. but it does not know how it got it. It picks up on the nuances of the directives, but if it relied in the past on reading the system  to complete the operation then it will get confused. BUT for user flow, the model gets the hang of the way things work. and over a long period of time has optimized itsself. this is ALL LOST after a reload even with some preliminary context. there would be no point in a state save if I can reconstruct it just by feeding it back all the context via plain text. But if I can keep the nuances that the engine picked up, and just give it back its original plain text system message, but a new session. I surmise it would improve naturally.  Since I have switched over to your engine. I lost the state save function. So I cannot further my experiment. but on the good side. we can load enormous contexts now adays. things have become streamlined. I see you added the raw bindings. I am not sure if I am smart enough to do the middle-ware part of the statesave. If you see value in what I mentioned, maybe a state save will be as innovative a the flash-attention addition's.

**Comment by dranger003** [comment]
I added the native state management API last week, you should try to use `llama_state_load_file` and `llama_state_save_file` like the main repo does.

**Comment by HarvieKrumpet** [comment]
But in order to use those state bindings I need to pass in the llm context handle. You have made those private. So no way to gain access into the llmEngine class (If I obey the abstraction)

Besides I would be forced to include the usings for Native in areas where I should not. Which means I will further break the package as soon as I hack in to turn it public.

It would be best if all these state calls are a few public functions within the LLmEngine and another abstraction to encapsulate the returned state structure with the ability to stream the  byte[]  to and from it. (without breaking the abstraction). as well as easy access to know the true context size.

**Comment by HarvieKrumpet** [comment]
need a formalized way to gain access to the llama_context you currently have it "private".  Currently I either need to hack into the llmEngine and set it to public to get the pointer.  if these functions were public to the LLMEngine this would be appropriate.  And I need to keep tabs on the current context state size (without loading/saving it)

**Comment by dranger003** [comment]
I exposed the native handles for now, until I can find some time to add and test support for loading and saving state. Feel to propose an implementation as a PR, if you want.

**Comment by HarvieKrumpet** [comment]
Was getting ready to tackle a proper load/save state using your new access to the context handles.  But it appears I need to also save the tokens processed as well.  As per this llama.cpp example https://github.com/ggerganov/llama.cpp/blob/master/examples/save-load-state/save-load-state.cpp

But of course your tokens have long been processed and purged by the time I get access. I suppose if your LLMEngine class keeps them (until the next prompting) I could save it out. 

My goal is to emulate the llamma.cpp --prompt-cache feature to at least reduce the time it takes to process my system prompt as mine is very large. 

Sort of looking like it would be better if  I set a flag in your llmPrompt class to handle the entire save as you have all the pieces during your worker thread.  To do this outside of that thread is going to be messy.  I propose  the llmengine has a savestate filename field for your reference. And then I just set a simple bool to indicate for your llmprompt to fire off a savestate in your thread while in the midst of processing the response. Then I don't even need to touch any native llama calls. For the load portion this could be special version of the loadmodel call. (unless you see some benefit to load the state over an existing context)

Other than this, your lib is performing like a champ

**Comment by dranger003** [comment]
Looks like some discussion are sparking again on a higher level library (see https://github.com/ggerganov/llama.cpp/issues/5215) which I think will have load/save state support. If that is the case, then I think I would probably just wrap that library instead. At this stage, they actually removed chat template support so I will be waiting before pull the upstream code.

**Comment by dranger003** [comment]
Closing for now, re-open if you need to further discuss.
