### ISSUE TITLE
Progress callback never called

### ISSUE THREAD

**Issue by HarvieKrumpet** [dranger003/llama.cpp-dotnet#17]
Tried to redirect the action progress callback., did not see it hit the breakpoint. It appears the engine also does not call its own callback
Never hit the breakpoint in here either.
        private static unsafe sbyte _ProgressCallback(float progress, void* state)
        {
            var callback = (Action<float>?)GCHandle.FromIntPtr(new(state)).Target;
            callback?.Invoke(progress * 100);
            return true ? 1 : 0;
        }

**Comment by dranger003** [comment]
Work fine for me, this is meant to be used in the client code, not in `LlmEngine`.

```csharp
llm.LoadModel(
    args[0],
    new LlmModelOptions(),
    (float progress) => { Console.Write($"{new string(' ', 32)}\rLoading model... {progress:0.00}%\r"); }
);
```

**Comment by dranger003** [comment]
Closing for now, re-open if you still are having an issue.
