### ISSUE TITLE
Dynamically loading different llama DLLs in a Windows client app

### ISSUE THREAD

**Issue by AshD** [dranger003/llama.cpp-dotnet#18]
I want to use it in a Windows client app, where I don't know if the user has a GPU and which GPU?

Is there a way, I can dynamically load the correct llama.dll 
No GPU - base llama.dll
Nvidia GPU - load from a folder that has Cuda 12 llama.dll and Cuda dlls
AMD GPU - Load from a folder that has clblast.dll and corresponding llama.dll

Would it work if I detect the correct situation and call the Windows LoadLibrary API with the corresponding llama.dll? Thanks.

**Comment by dranger003** [comment]
Look at this commit https://github.com/dranger003/llama.cpp-dotnet/commit/13c43adc03a3976003485c7c48b29b07c119df8b.

**Comment by AshD** [comment]
Thanks @dranger003 
It's working :-)

Not sure why the ResolveLibrary is being called multiple times though. Probably a windows dll loading thing.

**Comment by AshD** [comment]
Closing
