### ISSUE TITLE
Convert to GGUF

### ISSUE THREAD

**Issue by vietanh125** [dranger003/llama.cpp-dotnet#19]
Hi, could you tell me how did you convert the HF model to GGUF? I tried to convert this model [Linq-AI-Research/Linq-Embed-Mistral](https://huggingface.co/Linq-AI-Research/Linq-Embed-Mistral) but got KeyError. If possible, could you help convert it? 

Thank you.

**Comment by dranger003** [comment]
Pull the `e5-mistral` branch from https://github.com/dranger003/llama.cpp/tree/e5-mistral and `convert-hf-gguf.py` should work for that model, I added the tensor mappings.

Also, you need to change `MistralModel` with `MistralForCausalLM` in `config.json`.

**Comment by vietanh125** [comment]
That's really helpful. Thank you!
