### ISSUE TITLE
Latest version of llama.cpp breaks the lib

### ISSUE THREAD

**Issue by HarvieKrumpet** [dranger003/llama.cpp-dotnet#20]
After doing a pull and rebuild of the llama.cpp dll's cannot load a model without error now. I suspect a binding change somewhere will be needed.

**Comment by dranger003** [comment]
Yes, they have pushed a rework of the sampling interface, and it is API breaking. I'll take a look how extensive it is to update.

**Comment by dranger003** [comment]
Updated.
