### ISSUE TITLE
Yi/Orca/ChatML

### ISSUE THREAD

**Issue by HarvieKrumpet** [dranger003/llama.cpp-dotnet#22]
I have not been able to use a ChatML based on Orca or Yi.  I am not entirely sure how different ChatTemplates are detected and used by llama.cpp. All work except when it comes to Yi or Orca base models that use the ChatML format. Words run together as well as other issues. 
Perhaps you have some clue what needs to be done.

**Comment by dranger003** [comment]
Which HF models are you referring to? Can you provide the HF links to the models? I can take a look.

**Comment by HarvieKrumpet** [comment]
This for one would be a good example. 
dolphin-2.9.3-Yi-1.5-34B-32k-GGUF

output looks like this.
Hello!HowcanIassistyoutoday?

**Comment by dranger003** [comment]
Ah yes, I made a new commit try again and let me know if this is fixed.

**Comment by HarvieKrumpet** [comment]
Yes, totally fixed. This 01.ai model is very interesting. It is 34B but has the speed of a 7B. But also 32K context. And the only openSource AI out there. It also uses a very different set of Corpora for pure reasoning. Thank you for fixing this!  I have not tried any of the older Orca models, but I suspect they would be fixed with this patch!

**Comment by dranger003** [comment]
Yes, this should fix it for the other models as well.
