### ISSUE TITLE
locked up with latest llama.cpp update

### ISSUE THREAD

**Issue by HarvieKrumpet** [dranger003/llama.cpp-dotnet#26]
simply did a pull from llama.cpp repo. Now I hang at ```llama_sampler_init_tail_free()```
this is within the LlmEngine.cs

Not sure whats going on. I attempted to use a pre-built ggml.dll/llama.dll just to be sure and same result.

Excerpt below...

```
llama_sampler_chain_add(_sampler.Handle, llama_sampler_init_top_k(sequence.SamplingOptions.TopK));
hang-->_llama_sampler_chain_add(_sampler.Handle, llama_sampler_init_tail_free(sequence.SamplingOptions.TfsZ, 1));_
llama_sampler_chain_add(_sampler.Handle, llama_sampler_init_typical(sequence.SamplingOptions.TypicalP, 1));
llama_sampler_chain_add(_sampler.Handle, llama_sampler_init_top_p(sequence.SamplingOptions.TopP, 1));
llama_sampler_chain_add(_sampler.Handle, llama_sampler_init_min_p(sequence.SamplingOptions.MinP, 1));
llama_sampler_chain_add(_sampler.Handle, llama_sampler_init_temp(sequence.SamplingOptions.Temperature));
|```

**Comment by dranger003** [comment]
Yes, looks like they removed TFS sampling. And it seems they are doing some more upcoming sampling rework and so the code will break again soon. I updated the code for now.

**Comment by dranger003** [comment]
Closing for now, you can re-open if you still have an issue.
