### ISSUE TITLE
Couldn't get this to work in VS 2022

### ISSUE THREAD

**Issue by Webslug** [dranger003/llama.cpp-dotnet#5]
I tried several of the projects, this just won't build at all and I was hoping to try it out.  

![image](https://github.com/dranger003/llama.cpp-dotnet/assets/7551638/fd2a273f-fb0c-4ade-acf9-df3e019f7e71)

**Comment by dranger003** [comment]
This repo contains git submodules, downloading the source isn't going to work unless you restore the submodules as well. Check the quick start section of the readme, that should work.
