### ISSUE TITLE
Making cmake build optional?

### ISSUE THREAD

**Issue by drasticactions** [dranger003/llama.cpp-dotnet#9]
First, thank you for building a slim-line binding to these libraries. Having larger libraries with helper methods can be nice, but sometimes you just needed to pinvoke a thing so this existing is quite nice. I do have a question though:

https://github.com/dranger003/llama.cpp-dotnet/blob/master/LlamaCppLib/LlamaCppLib.csproj#L18-L55

https://github.com/dranger003/llama.cpp-dotnet/blob/master/BertCppLib/BertCppLib.csproj#L18-L54

I already have CI for building the native libraries, and I've also built them for other platforms I want to deploy to (Like macOS/Mac Catalyst). These msbuild scripts will always build against the submodule and reference the output, even when I don't want them to. In some cases, like on Mac, it won't run so it "works" but on Windows/Linux, if I want to target another platform (Like, Android) then I'm building and referencing libraries that won't work.

Would it be possible to make the cmake builds optional? They can be set as the default to run, but having it be something I can turn off would make it easier to use this source directly, instead of hacking on the code myself.

**Comment by dranger003** [comment]
Right, I think the MSBuild targets could benefit from having conditional checks.
Can you test using `Condition="'$(NativeLibraries)'!='OFF'"` and if that works then I'm happy to take a PR?

For example on: https://github.com/dranger003/llama.cpp-dotnet/blob/90b5ab74c006fd7c26fff33a9fda02565570d89b/LlamaCppLib/LlamaCppLib.csproj#L18 you could try:
```
<Target Name="CMakePrepareForBuild" BeforeTargets="PrepareForBuild;Clean" Condition="'$(NativeLibraries)'!='OFF'">
```
Then use `dotnet.exe build -p:NativeLibrairies=OFF`.

**Comment by dranger003** [comment]
Thanks!
